fixed notes function

diff --git a/configuration/.config/shell/alias b/configuration/.config/shell/alias
--- a/configuration/.config/shell/alias
+++ b/configuration/.config/shell/alias
@@ -66,8 +66,17 @@ search_man() {
 notes() {
     editor="${1:-nvim}"  # Use the first argument if provided, otherwise default to nvim
     (
-        cd "$NOTES_DIR"
-        "$editor" "$NOTES_DIR/$(tv files)"
+        cd "$NOTES_DIR" || exit 1  # Exit if NOTES_DIR cannot be changed to
+        file="$(tv files)"  # Capture the output of tv files
+
+        # Trim and sanitize the file name
+        sanitized_file=$(echo "$file" | sed 's/[{}]//g' | xargs)
+        if [[ -n "$sanitized_file" && -f "$sanitized_file" ]]; then
+            # Use the editor to open the selected file
+            "$editor" "$sanitized_file"
+        else
+            echo "Error: No valid file selected or file does not exist."
+        fi
     )
 }
 
